# Generated by Django 5.2.14 on 2026-08-11 14:50

import apps.accounts.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Usado para login. Deve ser único no sistema.",
                        max_length=254,
                        unique=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        help_text="Nome e sobrenome do usuário.",
                        max_length=200,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Formatos aceitos: JPG, PNG. Tamanho máximo: 2 MB.",
                        null=True,
                        upload_to="usuarios/fotos/%Y/%m/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Formato: (11) 99999-9999",
                        max_length=20,
                        validators=[apps.accounts.models.validate_telefone],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("America/Sao_Paulo", "Brasília / São Paulo (UTC-3)"),
                            ("America/Fortaleza", "Fortaleza / Recife (UTC-3)"),
                            ("America/Bahia", "Salvador (UTC-3)"),
                            ("America/Belem", "Belém (UTC-3)"),
                            ("America/Manaus", "Manaus (UTC-4)"),
                            ("America/Cuiaba", "Cuiabá (UTC-4)"),
                            ("America/Porto_Velho", "Porto Velho (UTC-4)"),
                            ("America/Boa_Vista", "Boa Vista (UTC-4)"),
                            ("America/Rio_Branco", "Rio Branco (UTC-5)"),
                            ("America/Noronha", "Fernando de Noronha (UTC-2)"),
                        ],
                        default="America/Sao_Paulo",
                        help_text="Fuso horário usado para exibição de datas e horários.",
                        max_length=50,
                        verbose_name="Fuso horário",
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Ativa o tema escuro na interface do sistema.",
                        verbose_name="Modo escuro",
                    ),
                ),
                (
                    "is_lider",
                    models.BooleanField(
                        default=False,
                        help_text="Permite acompanhar o progresso de discípulos vinculados.",
                        verbose_name="É líder",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para desativar a conta sem excluir o usuário. Usuários inativos não conseguem fazer login.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Permite acesso ao painel administrativo Django.",
                        verbose_name="Acesso ao admin",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Usado para login. Deve ser único no sistema.",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        help_text="Nome e sobrenome do usuário.",
                        max_length=200,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "foto",
                    models.TextField(
                        blank=True,
                        help_text="Formatos aceitos: JPG, PNG. Tamanho máximo: 2 MB.",
                        max_length=100,
                        null=True,
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Formato: (11) 99999-9999",
                        max_length=20,
                        validators=[apps.accounts.models.validate_telefone],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("America/Sao_Paulo", "Brasília / São Paulo (UTC-3)"),
                            ("America/Fortaleza", "Fortaleza / Recife (UTC-3)"),
                            ("America/Bahia", "Salvador (UTC-3)"),
                            ("America/Belem", "Belém (UTC-3)"),
                            ("America/Manaus", "Manaus (UTC-4)"),
                            ("America/Cuiaba", "Cuiabá (UTC-4)"),
                            ("America/Porto_Velho", "Porto Velho (UTC-4)"),
                            ("America/Boa_Vista", "Boa Vista (UTC-4)"),
                            ("America/Rio_Branco", "Rio Branco (UTC-5)"),
                            ("America/Noronha", "Fernando de Noronha (UTC-2)"),
                        ],
                        default="America/Sao_Paulo",
                        help_text="Fuso horário usado para exibição de datas e horários.",
                        max_length=50,
                        verbose_name="Fuso horário",
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Ativa o tema escuro na interface do sistema.",
                        verbose_name="Modo escuro",
                    ),
                ),
                (
                    "is_lider",
                    models.BooleanField(
                        default=False,
                        help_text="Permite acompanhar o progresso de discípulos vinculados.",
                        verbose_name="É líder",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para desativar a conta sem excluir o usuário. Usuários inativos não conseguem fazer login.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Permite acesso ao painel administrativo Django.",
                        verbose_name="Acesso ao admin",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Criado em"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Atualizado em"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Usuário",
                "verbose_name_plural": "historical Usuários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
