# Generated by Django 5.2.14 on 2026-05-28 00:18

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='is_lider',
            field=models.BooleanField(default=False, help_text='Permite acompanhar o progresso de discípulos vinculados.', verbose_name='É líder'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_lider',
            field=models.BooleanField(default=False, help_text='Permite acompanhar o progresso de discípulos vinculados.', verbose_name='É líder'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Ativa o tema escuro na interface do sistema.', verbose_name='Modo escuro'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Usado para login. Deve ser único no sistema.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='foto',
            field=models.TextField(blank=True, help_text='Formatos aceitos: JPG, PNG. Tamanho máximo: 2 MB.', max_length=100, null=True, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para desativar a conta sem excluir o usuário. Usuários inativos não conseguem fazer login.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Permite acesso ao painel administrativo Django.', verbose_name='Acesso ao admin'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='nome_completo',
            field=models.CharField(help_text='Nome e sobrenome do usuário.', max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=20, validators=[apps.accounts.models.validate_telefone], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='timezone',
            field=models.CharField(choices=[('America/Sao_Paulo', 'Brasília / São Paulo (UTC-3)'), ('America/Fortaleza', 'Fortaleza / Recife (UTC-3)'), ('America/Bahia', 'Salvador (UTC-3)'), ('America/Belem', 'Belém (UTC-3)'), ('America/Manaus', 'Manaus (UTC-4)'), ('America/Cuiaba', 'Cuiabá (UTC-4)'), ('America/Porto_Velho', 'Porto Velho (UTC-4)'), ('America/Boa_Vista', 'Boa Vista (UTC-4)'), ('America/Rio_Branco', 'Rio Branco (UTC-5)'), ('America/Noronha', 'Fernando de Noronha (UTC-2)')], default='America/Sao_Paulo', help_text='Fuso horário usado para exibição de datas e horários.', max_length=50, verbose_name='Fuso horário'),
        ),
    ]
