# Generated by Django 5.2.14 on 2026-05-28 01:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTrilha",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(max_length=220, verbose_name="Slug")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVOCIONAL", "Devocional"),
                            ("DISCIPULADO", "Discipulado"),
                        ],
                        default="DEVOCIONAL",
                        help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PUBLICADO", "Publicado"),
                            ("ARQUIVADO", "Arquivado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("PUBLICO", "Público"),
                            ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                            ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                        ],
                        default="PUBLICO",
                        max_length=30,
                        verbose_name="Acesso",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trilha",
                "verbose_name_plural": "historical Trilhas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "imagem_capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="estudo/modulos/%Y/%m/",
                        verbose_name="Imagem de Capa",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "ordering": ["trilha", "ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTema",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(max_length=220, verbose_name="Slug")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "duracao_estimada",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duração estimada (min)"
                    ),
                ),
                ("texto_base", models.TextField(verbose_name="Texto Base")),
                (
                    "tem_oracao",
                    models.BooleanField(default=False, verbose_name="Tem Oração?"),
                ),
                ("oracao", models.TextField(blank=True, verbose_name="Oração")),
                (
                    "tem_referencias",
                    models.BooleanField(
                        default=False, verbose_name="Tem Referências Cruzadas?"
                    ),
                ),
                (
                    "referencias_cruzadas",
                    models.TextField(blank=True, verbose_name="Referências Cruzadas"),
                ),
                (
                    "tem_estudo",
                    models.BooleanField(
                        default=False, verbose_name="Tem Estudo Aprofundado?"
                    ),
                ),
                (
                    "estudo",
                    models.TextField(blank=True, verbose_name="Estudo Aprofundado"),
                ),
                (
                    "tem_exemplo",
                    models.BooleanField(
                        default=False, verbose_name="Tem Exemplo Prático?"
                    ),
                ),
                (
                    "exemplo_pratico",
                    models.TextField(blank=True, verbose_name="Exemplo Prático"),
                ),
                (
                    "tem_conclusao",
                    models.BooleanField(default=True, verbose_name="Tem Conclusão?"),
                ),
                ("conclusao", models.TextField(blank=True, verbose_name="Conclusão")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estudo.modulo",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tema",
                "verbose_name_plural": "historical Temas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "duracao_estimada",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duração estimada (min)"
                    ),
                ),
                ("texto_base", models.TextField(verbose_name="Texto Base")),
                (
                    "tem_oracao",
                    models.BooleanField(default=False, verbose_name="Tem Oração?"),
                ),
                ("oracao", models.TextField(blank=True, verbose_name="Oração")),
                (
                    "tem_referencias",
                    models.BooleanField(
                        default=False, verbose_name="Tem Referências Cruzadas?"
                    ),
                ),
                (
                    "referencias_cruzadas",
                    models.TextField(blank=True, verbose_name="Referências Cruzadas"),
                ),
                (
                    "tem_estudo",
                    models.BooleanField(
                        default=False, verbose_name="Tem Estudo Aprofundado?"
                    ),
                ),
                (
                    "estudo",
                    models.TextField(blank=True, verbose_name="Estudo Aprofundado"),
                ),
                (
                    "tem_exemplo",
                    models.BooleanField(
                        default=False, verbose_name="Tem Exemplo Prático?"
                    ),
                ),
                (
                    "exemplo_pratico",
                    models.TextField(blank=True, verbose_name="Exemplo Prático"),
                ),
                (
                    "tem_conclusao",
                    models.BooleanField(default=True, verbose_name="Tem Conclusão?"),
                ),
                ("conclusao", models.TextField(blank=True, verbose_name="Conclusão")),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas",
                        to="estudo.modulo",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
                "ordering": ["modulo", "ordem"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgressoTema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos_estudo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="estudo.tema",
                        verbose_name="Tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Tema",
                "verbose_name_plural": "Progressos de Temas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Trilha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="Slug"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVOCIONAL", "Devocional"),
                            ("DISCIPULADO", "Discipulado"),
                        ],
                        default="DEVOCIONAL",
                        help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PUBLICADO", "Publicado"),
                            ("ARQUIVADO", "Arquivado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("PUBLICO", "Público"),
                            ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                            ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                        ],
                        default="PUBLICO",
                        max_length=30,
                        verbose_name="Acesso",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trilha",
                "verbose_name_plural": "Trilhas",
                "ordering": ["ordem", "titulo"],
                "permissions": [
                    ("ver_trilha_restrita", "Pode ver trilhas com permissão específica")
                ],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="modulo",
            name="trilha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modulos",
                to="estudo.trilha",
                verbose_name="Trilha",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalModulo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(max_length=220, verbose_name="Slug")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "imagem_capa",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Imagem de Capa",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trilha",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estudo.trilha",
                        verbose_name="Trilha",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Módulo",
                "verbose_name_plural": "historical Módulos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RelacaoLiderDiscipulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "discipulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lideres_vinculados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Discípulo",
                    ),
                ),
                (
                    "lider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipulos_vinculados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Líder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relação Líder-Discípulo",
                "verbose_name_plural": "Relações Líder-Discípulo",
                "indexes": [
                    models.Index(
                        fields=["lider"], name="estudo_rela_lider_i_addad7_idx"
                    ),
                    models.Index(
                        fields=["discipulo"], name="estudo_rela_discipu_62720c_idx"
                    ),
                ],
                "unique_together": {("lider", "discipulo")},
            },
        ),
        migrations.AddIndex(
            model_name="tema",
            index=models.Index(
                fields=["modulo", "ordem"], name="estudo_tema_modulo__1f710b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tema",
            unique_together={("modulo", "ordem")},
        ),
        migrations.AddIndex(
            model_name="progressotema",
            index=models.Index(
                fields=["usuario", "tema"], name="estudo_prog_usuario_73f192_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressotema",
            index=models.Index(
                fields=["usuario"], name="estudo_prog_usuario_81d8f0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progressotema",
            unique_together={("usuario", "tema")},
        ),
        migrations.AddIndex(
            model_name="modulo",
            index=models.Index(
                fields=["trilha", "ordem"], name="estudo_modu_trilha__b0e7df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modulo",
            unique_together={("trilha", "ordem")},
        ),
    ]
