# Generated by Django 5.2.14 on 2026-05-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmodulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                ],
                default="PUBLICO",
                help_text="Regra mais restritiva entre trilha e módulo se aplica.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AddField(
            model_name="historicaltema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                ],
                default="PUBLICO",
                help_text="Regra mais restritiva entre trilha, módulo e tema se aplica.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                ],
                default="PUBLICO",
                help_text="Regra mais restritiva entre trilha e módulo se aplica.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AddField(
            model_name="tema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                ],
                default="PUBLICO",
                help_text="Regra mais restritiva entre trilha, módulo e tema se aplica.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
    ]
