# Generated by Django 5.2.14 on 2026-05-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("estudo", "0002_modulo_tema_acesso"),
    ]

    operations = [
        migrations.AddField(
            model_name="trilha",
            name="grupos",
            field=models.ManyToManyField(
                blank=True,
                help_text='Ativo somente quando Acesso = "Permissão específica". O usuário precisa pertencer a pelo menos um dos grupos listados. Lembre-se de adicionar o grupo ao usuário no seu cadastro.',
                related_name="trilhas_acessiveis",
                to="auth.group",
                verbose_name="Grupos com acesso",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmodulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
    ]
