# Generated by Django 5.2.14 on 2026-05-29 02:06

import apps.estudo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0003_trilha_grupos_m2m_acesso_basico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodulo",
            name="imagem_capa",
            field=models.TextField(
                blank=True,
                help_text="Formatos aceitos: JPEG (.jpg, .jpeg) e PNG (.png). A imagem será redimensionada para 800×450 px (16:9) automaticamente.",
                max_length=100,
                null=True,
                validators=[apps.estudo.models.validar_formato_imagem],
                verbose_name="Imagem de Capa",
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="imagem_capa",
            field=models.ImageField(
                blank=True,
                help_text="Formatos aceitos: JPEG (.jpg, .jpeg) e PNG (.png). A imagem será redimensionada para 800×450 px (16:9) automaticamente.",
                null=True,
                upload_to="estudo/modulos/%Y/%m/",
                validators=[apps.estudo.models.validar_formato_imagem],
                verbose_name="Imagem de Capa",
            ),
        ),
        migrations.DeleteModel(
            name="RelacaoLiderDiscipulo",
        ),
    ]
