# Generated by Django 5.2.14 on 2026-05-29 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0004_remove_relacao_lider_discipulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstudoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex.: 'Estudo de João 3:16 — O Amor de Deus'.",
                        max_length=300,
                        verbose_name="Título do Estudo",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        help_text="Ex.: João 3:16 · Romanos 8:1-11 · Salmo 23.",
                        max_length=100,
                        verbose_name="Referência Bíblica",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "texto_biblico",
                    models.TextField(
                        blank=True,
                        help_text="Cole aqui o(s) versículo(s) que serão estudados.",
                        verbose_name="Texto Bíblico",
                    ),
                ),
                (
                    "contexto_anterior",
                    models.TextField(
                        blank=True,
                        help_text="O que acontece antes do texto? Qual é o cenário imediatamente anterior?",
                        verbose_name="Contexto Anterior",
                    ),
                ),
                (
                    "contexto_posterior",
                    models.TextField(
                        blank=True,
                        help_text="O que acontece depois do texto? Como o contexto seguinte ilumina o trecho?",
                        verbose_name="Contexto Posterior",
                    ),
                ),
                (
                    "versiculos_relacionados",
                    models.TextField(
                        blank=True,
                        help_text="Concordância bíblica: liste referências que tratam do mesmo tema ou palavra-chave.",
                        verbose_name="Versículos Relacionados",
                    ),
                ),
                (
                    "palavra_central",
                    models.CharField(
                        blank=True,
                        help_text="A palavra mais importante do texto; eixo do estudo.",
                        max_length=200,
                        verbose_name="Palavra Central",
                    ),
                ),
                (
                    "palavra_repetida",
                    models.CharField(
                        blank=True,
                        help_text="Palavra com maior frequência no trecho — repetição geralmente indica ênfase.",
                        max_length=200,
                        verbose_name="Palavra que se Repete",
                    ),
                ),
                (
                    "palavra_aprofundar",
                    models.CharField(
                        blank=True,
                        help_text="Palavra que merece pesquisa lexical (hebraico/grego) ou teológica.",
                        max_length=200,
                        verbose_name="Palavra a Aprofundar",
                    ),
                ),
                (
                    "sinonimos",
                    models.TextField(
                        blank=True,
                        help_text="Sinônimos e termos equivalentes da palavra central ou palavra a aprofundar.",
                        verbose_name="Sinônimos",
                    ),
                ),
                (
                    "traducao_hebraico",
                    models.TextField(
                        blank=True,
                        help_text="Sentido do termo no hebraico original (para textos do AT). Use Strong's ou léxico BDB.",
                        verbose_name="Tradução / Hebraico",
                    ),
                ),
                (
                    "traducao_grego",
                    models.TextField(
                        blank=True,
                        help_text="Sentido do termo no grego original (para textos do NT). Use Strong's, BDAG ou Thayer.",
                        verbose_name="Tradução / Grego",
                    ),
                ),
                (
                    "traducao_latim",
                    models.TextField(
                        blank=True,
                        help_text="Como a Vulgata Latina traduz o termo — útil para rastrear influência teológica medieval.",
                        verbose_name="Tradução / Latim",
                    ),
                ),
                (
                    "traducao_ingles",
                    models.TextField(
                        blank=True,
                        help_text="Como versões em inglês (KJV, ESV, NASB) rendem o termo — amplia o espectro semântico.",
                        verbose_name="Tradução / Inglês",
                    ),
                ),
                (
                    "observacoes_portugues",
                    models.TextField(
                        blank=True,
                        help_text="Nuances da tradução para o português: diferenças entre ARC, ARA, NVI, NVT, etc.",
                        verbose_name="Observações para o Português",
                    ),
                ),
                (
                    "onde_esta_cristo",
                    models.TextField(
                        blank=True,
                        help_text="Leitura cristológica do texto: como ele aponta para Cristo (AT) ou revela Cristo (NT)?",
                        verbose_name="Onde Está Cristo",
                    ),
                ),
                (
                    "uso_antigo_testamento",
                    models.TextField(
                        blank=True,
                        help_text="Como este texto/palavra/tema é tratado no AT? Há prefigurações, tipos ou citações?",
                        verbose_name="Uso no Antigo Testamento",
                    ),
                ),
                (
                    "uso_novo_testamento",
                    models.TextField(
                        blank=True,
                        help_text="O NT cita, cumpre ou expande este texto? Onde e como?",
                        verbose_name="Uso no Novo Testamento",
                    ),
                ),
                (
                    "uso_historico_grego",
                    models.TextField(
                        blank=True,
                        help_text="Como o termo era usado na literatura grega extrabíblica (Homero, Tucídides, LXX)?",
                        verbose_name="Uso Histórico Grego",
                    ),
                ),
                (
                    "uso_historico_filosofia_antiga",
                    models.TextField(
                        blank=True,
                        help_text="Platão, Aristóteles, Estoicos: qual o sentido do conceito na filosofia clássica?",
                        verbose_name="Uso na Filosofia Antiga",
                    ),
                ),
                (
                    "filosofia_moderna",
                    models.TextField(
                        blank=True,
                        help_text="Como pensadores modernos (Kant, Hegel, Kierkegaard, etc.) tratam tema semelhante?",
                        verbose_name="Filosofia Moderna",
                    ),
                ),
                (
                    "genero_literario",
                    models.TextField(
                        blank=True,
                        help_text="Narrativa, poesia, lei, profecia, epístola, apocalipse? Como isso afeta a interpretação?",
                        verbose_name="Gênero Literário",
                    ),
                ),
                (
                    "cultura",
                    models.TextField(
                        blank=True,
                        help_text="Costumes, contexto socioeconômico, político e religioso do mundo do autor/destinatário.",
                        verbose_name="Cultura",
                    ),
                ),
                (
                    "intencao_autor",
                    models.TextField(
                        blank=True,
                        help_text="O que o autor humano pretendia comunicar ao seu auditório original?",
                        verbose_name="Intenção do Autor",
                    ),
                ),
                (
                    "quem_fala",
                    models.CharField(
                        blank=True,
                        help_text="Identifique o locutor: Deus, um profeta, o apóstolo, um personagem da narrativa.",
                        max_length=300,
                        verbose_name="Quem está falando?",
                    ),
                ),
                (
                    "para_quem",
                    models.CharField(
                        blank=True,
                        help_text="Identifique o(s) destinatário(s) original(is).",
                        max_length=300,
                        verbose_name="Para quem?",
                    ),
                ),
                (
                    "sobre_o_que",
                    models.TextField(
                        blank=True,
                        help_text="Qual é o assunto central que o texto aborda?",
                        verbose_name="Sobre o quê?",
                    ),
                ),
                (
                    "qual_objetivo",
                    models.TextField(
                        blank=True,
                        help_text="O texto visa ensinar, corrigir, consolar, exortar, profetizar? Qual a finalidade?",
                        verbose_name="Qual o objetivo?",
                    ),
                ),
                (
                    "o_que_exige_de_mim",
                    models.TextField(
                        blank=True,
                        help_text="Qual a demanda prática, espiritual ou ética que este texto impõe ao leitor?",
                        verbose_name="O que exige de mim?",
                    ),
                ),
                (
                    "incluir_introducao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Introdução",
                    ),
                ),
                (
                    "introducao",
                    models.TextField(
                        blank=True,
                        help_text="Contextualize o tema para o ouvinte/leitor: gancho, problema, relevância.",
                        verbose_name="Introdução",
                    ),
                ),
                (
                    "incluir_explicacao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Explicação",
                    ),
                ),
                (
                    "explicacao",
                    models.TextField(
                        blank=True,
                        help_text="O que o texto diz? Exegese e exposição versículo a versículo.",
                        verbose_name="Explicação",
                    ),
                ),
                (
                    "incluir_aplicacao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Aplicação",
                    ),
                ),
                (
                    "aplicacao",
                    models.TextField(
                        blank=True,
                        help_text="Como este texto deve transformar a vida do ouvinte? Exemplos concretos.",
                        verbose_name="Aplicação",
                    ),
                ),
                (
                    "incluir_conclusao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Conclusão",
                    ),
                ),
                (
                    "conclusao",
                    models.TextField(
                        blank=True,
                        help_text="Fechamento do estudo: síntese, chamada à ação ou convite.",
                        verbose_name="Conclusão",
                    ),
                ),
                (
                    "incluir_oracao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Oração",
                    ),
                ),
                (
                    "oracao",
                    models.TextField(
                        blank=True,
                        help_text="Sugestão de oração para encerrar o estudo ou o culto.",
                        verbose_name="Oração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudo Pessoal",
                "verbose_name_plural": "Estudos Pessoais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TopicoEstudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incluir",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para ocultar este tópico na exportação e no template.",
                        verbose_name="Incluir",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex.: 'A soberania de Deus na criação'.",
                        max_length=300,
                        verbose_name="Título do Tópico",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        blank=True,
                        help_text="Desenvolvimento do tópico: pontos de apoio, versículos, ilustrações.",
                        verbose_name="Conteúdo",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Define a sequência de apresentação dos tópicos.",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos",
                        to="estudo.estudopessoal",
                        verbose_name="Estudo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
                "ordering": ["ordem"],
            },
        ),
    ]
