# Generated by Django 5.2.14 on 2026-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0005_add_estudopessoal_topico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudopessoal",
            name="aplicacao",
            field=models.TextField(
                blank=True,
                help_text="Como este texto deve transformar a vida do ouvinte? Exemplos concretos.",
                null=True,
                verbose_name="Aplicação",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="conclusao",
            field=models.TextField(
                blank=True,
                help_text="Fechamento do estudo: síntese, chamada à ação ou convite.",
                null=True,
                verbose_name="Conclusão",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="contexto_anterior",
            field=models.TextField(
                blank=True,
                help_text="O que acontece antes do texto? Qual é o cenário imediatamente anterior?",
                null=True,
                verbose_name="Contexto Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="contexto_posterior",
            field=models.TextField(
                blank=True,
                help_text="O que acontece depois do texto? Como o contexto seguinte ilumina o trecho?",
                null=True,
                verbose_name="Contexto Posterior",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="cultura",
            field=models.TextField(
                blank=True,
                help_text="Costumes, contexto socioeconômico, político e religioso do mundo do autor/destinatário.",
                null=True,
                verbose_name="Cultura",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="explicacao",
            field=models.TextField(
                blank=True,
                help_text="O que o texto diz? Exegese e exposição versículo a versículo.",
                null=True,
                verbose_name="Explicação",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="filosofia_moderna",
            field=models.TextField(
                blank=True,
                help_text="Como pensadores modernos (Kant, Hegel, Kierkegaard, etc.) tratam tema semelhante?",
                null=True,
                verbose_name="Filosofia Moderna",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="genero_literario",
            field=models.TextField(
                blank=True,
                help_text="Narrativa, poesia, lei, profecia, epístola, apocalipse? Como isso afeta a interpretação?",
                null=True,
                verbose_name="Gênero Literário",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="intencao_autor",
            field=models.TextField(
                blank=True,
                help_text="O que o autor humano pretendia comunicar ao seu auditório original?",
                null=True,
                verbose_name="Intenção do Autor",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="introducao",
            field=models.TextField(
                blank=True,
                help_text="Contextualize o tema para o ouvinte/leitor: gancho, problema, relevância.",
                null=True,
                verbose_name="Introdução",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="o_que_exige_de_mim",
            field=models.TextField(
                blank=True,
                help_text="Qual a demanda prática, espiritual ou ética que este texto impõe ao leitor?",
                null=True,
                verbose_name="O que exige de mim?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="observacoes_portugues",
            field=models.TextField(
                blank=True,
                help_text="Nuances da tradução para o português: diferenças entre ARC, ARA, NVI, NVT, etc.",
                null=True,
                verbose_name="Observações para o Português",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="onde_esta_cristo",
            field=models.TextField(
                blank=True,
                help_text="Leitura cristológica do texto: como ele aponta para Cristo (AT) ou revela Cristo (NT)?",
                null=True,
                verbose_name="Onde Está Cristo",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="oracao",
            field=models.TextField(
                blank=True,
                help_text="Sugestão de oração para encerrar o estudo ou o culto.",
                null=True,
                verbose_name="Oração",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="palavra_aprofundar",
            field=models.CharField(
                blank=True,
                help_text="Palavra que merece pesquisa lexical (hebraico/grego) ou teológica.",
                max_length=200,
                null=True,
                verbose_name="Palavra a Aprofundar",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="palavra_central",
            field=models.CharField(
                blank=True,
                help_text="A palavra mais importante do texto; eixo do estudo.",
                max_length=200,
                null=True,
                verbose_name="Palavra Central",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="palavra_repetida",
            field=models.CharField(
                blank=True,
                help_text="Palavra com maior frequência no trecho — repetição geralmente indica ênfase.",
                max_length=200,
                null=True,
                verbose_name="Palavra que se Repete",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="para_quem",
            field=models.CharField(
                blank=True,
                help_text="Identifique o(s) destinatário(s) original(is).",
                max_length=300,
                null=True,
                verbose_name="Para quem?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="qual_objetivo",
            field=models.TextField(
                blank=True,
                help_text="O texto visa ensinar, corrigir, consolar, exortar, profetizar? Qual a finalidade?",
                null=True,
                verbose_name="Qual o objetivo?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="quem_fala",
            field=models.CharField(
                blank=True,
                help_text="Identifique o locutor: Deus, um profeta, o apóstolo, um personagem da narrativa.",
                max_length=300,
                null=True,
                verbose_name="Quem está falando?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="referencia",
            field=models.CharField(
                blank=True,
                help_text="Ex.: João 3:16 · Romanos 8:1-11 · Salmo 23.",
                max_length=100,
                null=True,
                verbose_name="Referência Bíblica",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="sinonimos",
            field=models.TextField(
                blank=True,
                help_text="Sinônimos e termos equivalentes da palavra central ou palavra a aprofundar.",
                null=True,
                verbose_name="Sinônimos",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="sobre_o_que",
            field=models.TextField(
                blank=True,
                help_text="Qual é o assunto central que o texto aborda?",
                null=True,
                verbose_name="Sobre o quê?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="texto_biblico",
            field=models.TextField(
                blank=True,
                help_text="Cole aqui o(s) versículo(s) que serão estudados.",
                null=True,
                verbose_name="Texto Bíblico",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Ex.: 'Estudo de João 3:16 — O Amor de Deus'.",
                max_length=300,
                null=True,
                verbose_name="Título do Estudo",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="traducao_grego",
            field=models.TextField(
                blank=True,
                help_text="Sentido do termo no grego original (para textos do NT). Use Strong's, BDAG ou Thayer.",
                null=True,
                verbose_name="Tradução / Grego",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="traducao_hebraico",
            field=models.TextField(
                blank=True,
                help_text="Sentido do termo no hebraico original (para textos do AT). Use Strong's ou léxico BDB.",
                null=True,
                verbose_name="Tradução / Hebraico",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="traducao_ingles",
            field=models.TextField(
                blank=True,
                help_text="Como versões em inglês (KJV, ESV, NASB) rendem o termo — amplia o espectro semântico.",
                null=True,
                verbose_name="Tradução / Inglês",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="traducao_latim",
            field=models.TextField(
                blank=True,
                help_text="Como a Vulgata Latina traduz o termo — útil para rastrear influência teológica medieval.",
                null=True,
                verbose_name="Tradução / Latim",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="uso_antigo_testamento",
            field=models.TextField(
                blank=True,
                help_text="Como este texto/palavra/tema é tratado no AT? Há prefigurações, tipos ou citações?",
                null=True,
                verbose_name="Uso no Antigo Testamento",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="uso_historico_filosofia_antiga",
            field=models.TextField(
                blank=True,
                help_text="Platão, Aristóteles, Estoicos: qual o sentido do conceito na filosofia clássica?",
                null=True,
                verbose_name="Uso na Filosofia Antiga",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="uso_historico_grego",
            field=models.TextField(
                blank=True,
                help_text="Como o termo era usado na literatura grega extrabíblica (Homero, Tucídides, LXX)?",
                null=True,
                verbose_name="Uso Histórico Grego",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="uso_novo_testamento",
            field=models.TextField(
                blank=True,
                help_text="O NT cita, cumpre ou expande este texto? Onde e como?",
                null=True,
                verbose_name="Uso no Novo Testamento",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="versiculos_relacionados",
            field=models.TextField(
                blank=True,
                help_text="Concordância bíblica: liste referências que tratam do mesmo tema ou palavra-chave.",
                null=True,
                verbose_name="Versículos Relacionados",
            ),
        ),
    ]
