# Generated by Django 5.2.14 on 2026-06-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0008_limpar_imagem_capa_legada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmodulo",
            name="imagem_capa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("devocional.jpg", "Devocional"),
                    ("discipulado.jpg", "Discipulado"),
                    ("estudopessoal.jpg", "Estudo Pessoal"),
                ],
                default="",
                help_text="Escolha a imagem que representa o tipo de conteúdo deste módulo.",
                max_length=50,
                null=True,
                verbose_name="Imagem de Capa",
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="imagem_capa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("devocional.jpg", "Devocional"),
                    ("discipulado.jpg", "Discipulado"),
                    ("estudopessoal.jpg", "Estudo Pessoal"),
                ],
                default="",
                help_text="Escolha a imagem que representa o tipo de conteúdo deste módulo.",
                max_length=50,
                null=True,
                verbose_name="Imagem de Capa",
            ),
        ),
    ]
