# Generated by Django 5.2.14 on 2026-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0009_alter_historicalmodulo_imagem_capa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudopessoal",
            name="gramatica",
            field=models.TextField(
                blank=True,
                help_text="Análise gramatical do texto: estrutura das frases, verbos, tempos, modos e formas gramaticais relevantes.",
                null=True,
                verbose_name="Gramática",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="traducao_original",
            field=models.TextField(
                blank=True,
                help_text="Análise do texto no idioma original (hebraico ou grego): transliteração, forma verbal, raiz e notas lexicais.",
                null=True,
                verbose_name="Tradução / Original",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltema",
            name="estudo",
            field=models.TextField(blank=True, verbose_name="Estudo  "),
        ),
        migrations.AlterField(
            model_name="historicaltema",
            name="tem_estudo",
            field=models.BooleanField(default=False, verbose_name="Tem Estudo  ?"),
        ),
        migrations.AlterField(
            model_name="tema",
            name="estudo",
            field=models.TextField(blank=True, verbose_name="Estudo  "),
        ),
        migrations.AlterField(
            model_name="tema",
            name="tem_estudo",
            field=models.BooleanField(default=False, verbose_name="Tem Estudo  ?"),
        ),
    ]
