# Generated by Django 5.2.14 on 2026-07-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0010_estudopessoal_gramatica_traducao_original"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estudopessoal",
            options={
                "ordering": ["-criado_em"],
                "permissions": [
                    ("ver_estudopessoal", "Pode visualizar estudos pessoais"),
                    ("ver_hermeneutica_estudopessoal", "Pode ver seção Hermenêutica"),
                    ("ver_exegese_estudopessoal", "Pode ver seção Exegese"),
                    ("ver_homiletica_estudopessoal", "Pode ver seção Homilética"),
                    ("ver_topicos_estudopessoal", "Pode ver tópicos do estudo"),
                    ("exportar_estudopessoal", "Pode exportar estudos pessoais"),
                ],
                "verbose_name": "Estudo Pessoal",
                "verbose_name_plural": "Estudos Pessoais",
            },
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="cultura",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="filosofia_moderna",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="genero_literario",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="gramatica",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="intencao_autor",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="palavra_aprofundar",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="palavra_repetida",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="sinonimos",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="traducao_grego",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="traducao_hebraico",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="traducao_ingles",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="traducao_latim",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="traducao_original",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="uso_antigo_testamento",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="uso_historico_filosofia_antiga",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="uso_historico_grego",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="uso_novo_testamento",
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="contexto_geral_escrituras",
            field=models.TextField(
                blank=True,
                help_text="Como este texto se encaixa no contexto geral da Bíblia? Ex.: Capítulo inteiro, livro, etc.",
                null=True,
                verbose_name="Contexto Geral das Escrituras",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="incluir_exegese",
            field=models.BooleanField(
                default=True,
                help_text="Marque para incluir toda a seção de Exegese na exportação.",
                verbose_name="Incluir Exegese",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="incluir_hermeneutica",
            field=models.BooleanField(
                default=True,
                help_text="Marque para incluir toda a seção de Hermenêutica na exportação.",
                verbose_name="Incluir Hermenêutica",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="permissao",
            field=models.CharField(
                choices=[
                    ("SOMENTE_SUPERADMIN", "Somente Superadmin"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PUBLICO", "Público"),
                ],
                default="SOMENTE_SUPERADMIN",
                help_text="Define quem pode visualizar este estudo nos templates.",
                max_length=30,
                verbose_name="Permissão de Acesso",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="personagens",
            field=models.TextField(
                blank=True,
                help_text="Liste os personagens presentes no texto: protagonistas, antagonistas e figuras secundárias.",
                null=True,
                verbose_name="Personagens",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="traducoes",
            field=models.TextField(
                blank=True,
                help_text="Sentido do termo no hebraico original (para textos do AT). Use Strong's ou léxico BDB.",
                null=True,
                verbose_name="Tradução / Hebraico / Grego / Latim / Inglês",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="uso_antigo_novo_testamento",
            field=models.TextField(
                blank=True,
                help_text="Como este texto/palavra/tema é tratado no AT e NT? Há prefigurações, tipos ou citações?",
                null=True,
                verbose_name="Uso no Antigo e Novo Testamento",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="contexto_anterior",
            field=models.TextField(
                blank=True,
                help_text="Contexto Imediato e anterior ao versículo citado.",
                null=True,
                verbose_name="Contexto Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="contexto_posterior",
            field=models.TextField(
                blank=True,
                help_text="Contexto Imediato e posterior ao versículo citado.",
                null=True,
                verbose_name="Contexto Posterior",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="para_quem",
            field=models.CharField(
                blank=True,
                help_text="Identifique o(s) destinatário(s) original(is).",
                max_length=300,
                null=True,
                verbose_name="Público Original/Para quem?",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="quem_fala",
            field=models.CharField(
                blank=True,
                help_text="Identifique o locutor: Deus, um profeta, o apóstolo, um personagem da narrativa.",
                max_length=300,
                null=True,
                verbose_name="AUTOR/Quem está falando?",
            ),
        ),
    ]
