# Generated by Django 5.2.14 on 2026-07-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0011_add_permissao_personagens_estudopessoal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Ex.: 'Evangelhos', 'Cartas de Paulo', 'Sermões sobre Fé'.",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Ordem"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos de Estudos Pessoais",
                "ordering": ["ordem", "titulo"],
            },
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="topico",
            field=models.ForeignKey(
                blank=True,
                help_text="Tópico ao qual este estudo pertence.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudos",
                to="estudo.topico",
                verbose_name="Tópico",
            ),
        ),
    ]
