# Generated by Django 5.2.14 on 2026-07-02 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0012_add_topico_estudopessoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="topico",
            name="permissao",
            field=models.CharField(
                choices=[
                    ("SOMENTE_SUPERADMIN", "Somente Superadmin"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PUBLICO", "Público"),
                ],
                default="SOMENTE_SUPERADMIN",
                help_text="Define quem pode visualizar todos os estudos deste tópico. Aplica-se a todos os EstudoPessoal dentro dele.",
                max_length=30,
                verbose_name="Permissão de Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="topico",
            field=models.ForeignKey(
                blank=True,
                help_text="Tópico ao qual este estudo pertence. A permissão do tópico se aplica a este estudo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudos",
                to="estudo.topico",
                verbose_name="Tópico",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrilha",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="trilha",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
    ]
