# Generated by Django 5.2.14 on 2026-07-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0013_topico_permissao_acesso_somente_proprietario"),
    ]

    operations = [
        migrations.AddField(
            model_name="topico",
            name="imagem_capa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("estudopessoal.jpg", "Estudo Pessoal"),
                    ("devocional.jpg", "Devocional"),
                    ("discipulado.jpg", "Discipulado"),
                ],
                default="estudopessoal.jpg",
                help_text="Imagem exibida nos cards (escolha da lista de imagens estáticas).",
                max_length=50,
                null=True,
                verbose_name="Imagem de Capa",
            ),
        ),
    ]
