# Generated by Django 5.2.14 on 2026-07-03 00:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0014_topico_imagem_capa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudopessoal",
            name="topico",
        ),
        migrations.RemoveField(
            model_name="estudopessoal",
            name="permissao",
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="SOMENTE_PROPRIETARIO",
                help_text="SOMENTE_PROPRIETARIO = apenas o criador (criado_por) pode visualizar. LOGIN_OBRIGATORIO = qualquer usuário logado. PUBLICO = todos.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuário a alterar este registro.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_atualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário que criou este registro.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Preenchido automaticamente ao desativar o registro.",
                null=True,
                verbose_name="Deletado em",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                verbose_name="Ativo",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="modulo",
            field=models.ForeignKey(
                blank=True,
                help_text="Módulo ao qual este estudo pertence (quando inserido em uma Trilha).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estudos_pessoais",
                to="estudo.modulo",
                verbose_name="Módulo",
            ),
        ),
        migrations.AddField(
            model_name="estudopessoal",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DEVOCIONAL", "Devocional"),
                    ("DISCIPULADO", "Discipulado"),
                    ("ESTUDO_PESSOAL", "Estudo Pessoal"),
                ],
                default="ESTUDO_PESSOAL",
                help_text="Classificação do estudo.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuários staff que podem marcar presença dos alunos neste módulo.",
                limit_choices_to={"is_staff": True},
                related_name="modulos_como_professor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professores",
            ),
        ),
        migrations.AddField(
            model_name="progressotema",
            name="marcado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Professor que registrou esta conclusão. Null = registrado pelo próprio aluno.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progressos_marcados_como_professor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Marcado por (Professor)",
            ),
        ),
        migrations.AddField(
            model_name="tema",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuários staff que podem marcar presença dos alunos neste tema.",
                limit_choices_to={"is_staff": True},
                related_name="temas_como_professor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professores",
            ),
        ),
        migrations.AddField(
            model_name="trilha",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuários staff que podem marcar presença dos alunos nesta trilha.",
                limit_choices_to={"is_staff": True},
                related_name="trilhas_como_professor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Professores",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                verbose_name="Atualizado em",
            ),
        ),
        migrations.AlterField(
            model_name="estudopessoal",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                verbose_name="Criado em",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmodulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso. SOMENTE_PROPRIETARIO = apenas o criador vê este módulo.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrilha",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DEVOCIONAL", "Devocional"),
                    ("DISCIPULADO", "Discipulado"),
                    ("ESTUDO_PESSOAL", "Estudo Pessoal"),
                ],
                default="DEVOCIONAL",
                help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso. SOMENTE_PROPRIETARIO = apenas o criador vê este módulo.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="tema",
            name="acesso",
            field=models.CharField(
                choices=[
                    ("PUBLICO", "Público"),
                    ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                    ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                    ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                ],
                default="PUBLICO",
                help_text="Controle fino de acesso; permissão por grupo é definida na Trilha.",
                max_length=30,
                verbose_name="Acesso",
            ),
        ),
        migrations.AlterField(
            model_name="trilha",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DEVOCIONAL", "Devocional"),
                    ("DISCIPULADO", "Discipulado"),
                    ("ESTUDO_PESSOAL", "Estudo Pessoal"),
                ],
                default="DEVOCIONAL",
                help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEstudoPessoal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora de criação (UTC, exibido em horário de Brasília).",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Data e hora da última alteração (UTC, exibido em horário de Brasília).",
                        verbose_name="Atualizado em",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Desmarque para desativar o registro sem excluí-lo do banco. Registros inativos não aparecem nas listagens padrão.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Preenchido automaticamente ao desativar o registro.",
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEVOCIONAL", "Devocional"),
                            ("DISCIPULADO", "Discipulado"),
                            ("ESTUDO_PESSOAL", "Estudo Pessoal"),
                        ],
                        default="ESTUDO_PESSOAL",
                        help_text="Classificação do estudo.",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 'Estudo de João 3:16 — O Amor de Deus'.",
                        max_length=300,
                        null=True,
                        verbose_name="Título do Estudo",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: João 3:16 · Romanos 8:1-11 · Salmo 23.",
                        max_length=100,
                        null=True,
                        verbose_name="Referência Bíblica",
                    ),
                ),
                (
                    "texto_biblico",
                    models.TextField(
                        blank=True,
                        help_text="Cole aqui o(s) versículo(s) que serão estudados.",
                        null=True,
                        verbose_name="Texto Bíblico",
                    ),
                ),
                (
                    "contexto_anterior",
                    models.TextField(
                        blank=True,
                        help_text="Contexto Imediato e anterior ao versículo citado.",
                        null=True,
                        verbose_name="Contexto Anterior",
                    ),
                ),
                (
                    "contexto_posterior",
                    models.TextField(
                        blank=True,
                        help_text="Contexto Imediato e posterior ao versículo citado.",
                        null=True,
                        verbose_name="Contexto Posterior",
                    ),
                ),
                (
                    "contexto_geral_escrituras",
                    models.TextField(
                        blank=True,
                        help_text="Como este texto se encaixa no contexto geral da Bíblia? Ex.: Capítulo inteiro, livro, etc.",
                        null=True,
                        verbose_name="Contexto Geral das Escrituras",
                    ),
                ),
                (
                    "versiculos_relacionados",
                    models.TextField(
                        blank=True,
                        help_text="Concordância bíblica: liste referências que tratam do mesmo tema ou palavra-chave.",
                        null=True,
                        verbose_name="Versículos Relacionados",
                    ),
                ),
                (
                    "palavra_central",
                    models.CharField(
                        blank=True,
                        help_text="A palavra mais importante do texto; eixo do estudo.",
                        max_length=200,
                        null=True,
                        verbose_name="Palavra Central",
                    ),
                ),
                (
                    "traducoes",
                    models.TextField(
                        blank=True,
                        help_text="Sentido do termo no hebraico original (para textos do AT). Use Strong's ou léxico BDB.",
                        null=True,
                        verbose_name="Tradução / Hebraico / Grego / Latim / Inglês",
                    ),
                ),
                (
                    "observacoes_portugues",
                    models.TextField(
                        blank=True,
                        help_text="Nuances da tradução para o português: diferenças entre ARC, ARA, NVI, NVT, etc.",
                        null=True,
                        verbose_name="Observações para o Português",
                    ),
                ),
                (
                    "uso_antigo_novo_testamento",
                    models.TextField(
                        blank=True,
                        help_text="Como este texto/palavra/tema é tratado no AT e NT? Há prefigurações, tipos ou citações?",
                        null=True,
                        verbose_name="Uso no Antigo e Novo Testamento",
                    ),
                ),
                (
                    "onde_esta_cristo",
                    models.TextField(
                        blank=True,
                        help_text="Leitura cristológica do texto: como ele aponta para Cristo (AT) ou revela Cristo (NT)?",
                        null=True,
                        verbose_name="Onde Está Cristo",
                    ),
                ),
                (
                    "quem_fala",
                    models.CharField(
                        blank=True,
                        help_text="Identifique o locutor: Deus, um profeta, o apóstolo, um personagem da narrativa.",
                        max_length=300,
                        null=True,
                        verbose_name="AUTOR/Quem está falando?",
                    ),
                ),
                (
                    "personagens",
                    models.TextField(
                        blank=True,
                        help_text="Liste os personagens presentes no texto: protagonistas, antagonistas e figuras secundárias.",
                        null=True,
                        verbose_name="Personagens",
                    ),
                ),
                (
                    "para_quem",
                    models.CharField(
                        blank=True,
                        help_text="Identifique o(s) destinatário(s) original(is).",
                        max_length=300,
                        null=True,
                        verbose_name="Público Original/Para quem?",
                    ),
                ),
                (
                    "sobre_o_que",
                    models.TextField(
                        blank=True,
                        help_text="Qual é o assunto central que o texto aborda?",
                        null=True,
                        verbose_name="Sobre o quê?",
                    ),
                ),
                (
                    "qual_objetivo",
                    models.TextField(
                        blank=True,
                        help_text="O texto visa ensinar, corrigir, consolar, exortar, profetizar? Qual a finalidade?",
                        null=True,
                        verbose_name="Qual o objetivo?",
                    ),
                ),
                (
                    "o_que_exige_de_mim",
                    models.TextField(
                        blank=True,
                        help_text="Qual a demanda prática, espiritual ou ética que este texto impõe ao leitor?",
                        null=True,
                        verbose_name="O que exige de mim?",
                    ),
                ),
                (
                    "incluir_hermeneutica",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir toda a seção de Hermenêutica na exportação.",
                        verbose_name="Incluir Hermenêutica",
                    ),
                ),
                (
                    "incluir_exegese",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir toda a seção de Exegese na exportação.",
                        verbose_name="Incluir Exegese",
                    ),
                ),
                (
                    "incluir_introducao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Introdução",
                    ),
                ),
                (
                    "introducao",
                    models.TextField(
                        blank=True,
                        help_text="Contextualize o tema para o ouvinte/leitor: gancho, problema, relevância.",
                        null=True,
                        verbose_name="Introdução",
                    ),
                ),
                (
                    "incluir_explicacao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Explicação",
                    ),
                ),
                (
                    "explicacao",
                    models.TextField(
                        blank=True,
                        help_text="O que o texto diz? Exegese e exposição versículo a versículo.",
                        null=True,
                        verbose_name="Explicação",
                    ),
                ),
                (
                    "incluir_aplicacao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Aplicação",
                    ),
                ),
                (
                    "aplicacao",
                    models.TextField(
                        blank=True,
                        help_text="Como este texto deve transformar a vida do ouvinte? Exemplos concretos.",
                        null=True,
                        verbose_name="Aplicação",
                    ),
                ),
                (
                    "incluir_conclusao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Conclusão",
                    ),
                ),
                (
                    "conclusao",
                    models.TextField(
                        blank=True,
                        help_text="Fechamento do estudo: síntese, chamada à ação ou convite.",
                        null=True,
                        verbose_name="Conclusão",
                    ),
                ),
                (
                    "incluir_oracao",
                    models.BooleanField(
                        default=True,
                        help_text="Marque para incluir esta seção na exportação e no template.",
                        verbose_name="Incluir Oração",
                    ),
                ),
                (
                    "oracao",
                    models.TextField(
                        blank=True,
                        help_text="Sugestão de oração para encerrar o estudo ou o culto.",
                        null=True,
                        verbose_name="Oração",
                    ),
                ),
                (
                    "acesso",
                    models.CharField(
                        choices=[
                            ("PUBLICO", "Público"),
                            ("LOGIN_OBRIGATORIO", "Login obrigatório"),
                            ("PERMISSAO_ESPECIFICA", "Permissão específica"),
                            ("SOMENTE_PROPRIETARIO", "Somente proprietário"),
                        ],
                        default="SOMENTE_PROPRIETARIO",
                        help_text="SOMENTE_PROPRIETARIO = apenas o criador (criado_por) pode visualizar. LOGIN_OBRIGATORIO = qualquer usuário logado. PUBLICO = todos.",
                        max_length=30,
                        verbose_name="Acesso",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Último usuário a alterar este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Usuário que criou este registro.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Módulo ao qual este estudo pertence (quando inserido em uma Trilha).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="estudo.modulo",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estudo Pessoal",
                "verbose_name_plural": "historical Estudos Pessoais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProgressoEstudoPessoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "estudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="estudo.estudopessoal",
                        verbose_name="Estudo Pessoal",
                    ),
                ),
                (
                    "marcado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Professor que registrou esta conclusão. Null = registrado pelo próprio aluno.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudos_pessoais_marcados_como_professor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Marcado por (Professor)",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos_estudo_pessoal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Estudo Pessoal",
                "verbose_name_plural": "Progressos de Estudos Pessoais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.DeleteModel(
            name="Topico",
        ),
        migrations.AddIndex(
            model_name="progressoestudopessoal",
            index=models.Index(
                fields=["usuario", "estudo"], name="estudo_prog_usuario_d3c32f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressoestudopessoal",
            index=models.Index(
                fields=["usuario"], name="estudo_prog_usuario_766bd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progressoestudopessoal",
            unique_together={("usuario", "estudo")},
        ),
    ]
