# Generated by Django 5.2.14 on 2026-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudo", "0015_estudopessoal_modulo_tipo_acesso_professor_progresso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressoestudopessoal",
            name="estudo",
        ),
        migrations.RemoveField(
            model_name="topicoestudo",
            name="estudo",
        ),
        migrations.RemoveField(
            model_name="historicalestudopessoal",
            name="atualizado_por",
        ),
        migrations.RemoveField(
            model_name="historicalestudopessoal",
            name="criado_por",
        ),
        migrations.RemoveField(
            model_name="historicalestudopessoal",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalestudopessoal",
            name="modulo",
        ),
        migrations.AlterUniqueTogether(
            name="progressoestudopessoal",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="progressoestudopessoal",
            name="marcado_por",
        ),
        migrations.RemoveField(
            model_name="progressoestudopessoal",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="historicalmodulo",
            name="imagem_capa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("devocional.jpg", "Devocional"),
                    ("discipulado.jpg", "Discipulado"),
                ],
                default="",
                help_text="Escolha a imagem que representa o tipo de conteúdo deste módulo.",
                max_length=50,
                null=True,
                verbose_name="Imagem de Capa",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrilha",
            name="tipo",
            field=models.CharField(
                choices=[("DEVOCIONAL", "Devocional"), ("DISCIPULADO", "Discipulado")],
                default="DEVOCIONAL",
                help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="modulo",
            name="imagem_capa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("devocional.jpg", "Devocional"),
                    ("discipulado.jpg", "Discipulado"),
                ],
                default="",
                help_text="Escolha a imagem que representa o tipo de conteúdo deste módulo.",
                max_length=50,
                null=True,
                verbose_name="Imagem de Capa",
            ),
        ),
        migrations.AlterField(
            model_name="trilha",
            name="tipo",
            field=models.CharField(
                choices=[("DEVOCIONAL", "Devocional"), ("DISCIPULADO", "Discipulado")],
                default="DEVOCIONAL",
                help_text="Devocional = acesso por permissão; Discipulado = envolve líder/discípulo.",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.DeleteModel(
            name="EstudoPessoal",
        ),
        migrations.DeleteModel(
            name="TopicoEstudo",
        ),
        migrations.DeleteModel(
            name="HistoricalEstudoPessoal",
        ),
        migrations.DeleteModel(
            name="ProgressoEstudoPessoal",
        ),
    ]
