# Generated by Django 5.2.14 on 2026-05-29 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SacSuporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("duvida", "Dúvida"),
                            ("sugestao", "Sugestão"),
                            ("reclamacao", "Reclamação"),
                            ("elogio", "Elogio"),
                        ],
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sac_mensagens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem SAC",
                "verbose_name_plural": "Mensagens SAC",
                "ordering": ["-criado_em"],
            },
        ),
    ]
