# Generated by Django 5.2.14 on 2026-05-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoEmail",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=255,
                        verbose_name="Servidor SMTP",
                    ),
                ),
                (
                    "porta",
                    models.PositiveIntegerField(
                        default=587,
                        help_text="587 para TLS (recomendado) · 465 para SSL · 25 para sem criptografia.",
                        verbose_name="Porta",
                    ),
                ),
                (
                    "usuario",
                    models.EmailField(
                        default="admin@managerontecsolutions.com.br",
                        max_length=254,
                        verbose_name="Usuário (e-mail remetente)",
                    ),
                ),
                (
                    "senha_criptografada",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        verbose_name="Senha (criptografada)",
                    ),
                ),
                (
                    "usar_tls",
                    models.BooleanField(
                        default=True,
                        help_text="Recomendado para a porta 587 (Gmail/Google Workspace).",
                        verbose_name="Usar TLS",
                    ),
                ),
                (
                    "usar_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Use para a porta 465. Não ative junto com TLS.",
                        verbose_name="Usar SSL",
                    ),
                ),
                (
                    "nome_exibicao",
                    models.CharField(
                        default="Devocional e Discipulado",
                        help_text="Nome que aparece no campo 'De:' dos e-mails enviados.",
                        max_length=100,
                        verbose_name="Nome de exibição",
                    ),
                ),
                (
                    "timeout_segundos",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Timeout de conexão (segundos)"
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail",
                "verbose_name_plural": "E-mail",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSessao",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tempo_sessao_minutos",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Tempo de inatividade antes de encerrar a sessão automaticamente. Padrão: 120 minutos. Somente superusuários podem alterar.",
                        verbose_name="Tempo de sessão (minutos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão",
                "verbose_name_plural": "Sessão",
            },
        ),
    ]
